# Generated by Django 4.0.6 on 2022-08-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingredient_reciperequirements_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
