# Generated by Django 4.0.6 on 2022-08-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_ingredient_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
    ]
